"""
╔═══════════════════════════════════════════════════════════════════════╗
║  PRICING_ENGINE.PY — Quantitative Probability & Signal Engine        ║
║                                                                       ║
║  Core math behind the trading strategy:                              ║
║  1. Rolling volatility estimation from tick data                     ║
║  2. True probability via Black-Scholes binary option model           ║
║  3. Mispricing detection (>8% gap between true prob & PM price)      ║
║  4. Latency arbitrage detection (spot cross vs stale PM book)        ║
║                                                                       ║
║  Mathematical Foundation:                                             ║
║  For a binary option (pays $1 if S > K at expiry, else $0):          ║
║                                                                       ║
║    d₂ = [ln(S/K) + (-0.5σ²)T] / (σ√T)                              ║
║    P(S > K) = Φ(d₂)                                                 ║
║                                                                       ║
║  Where Φ is the standard normal CDF, S is spot, K is strike,        ║
║  T is time-to-expiry (in years), σ is annualized volatility.        ║
║                                                                       ║
║  This is the same "cash-or-nothing" binary option formula used       ║
║  in traditional derivatives pricing, adapted for short-term          ║
║  prediction markets.                                                  ║
╚═══════════════════════════════════════════════════════════════════════╝
"""

import math
import time
import logging
from dataclasses import dataclass, field
from typing import Optional, List, Tuple
from collections import deque
from enum import Enum

import numpy as np
from scipy.stats import norm

from config import (
    MISPRICING_THRESHOLD, MISPRICING_EXIT_THRESHOLD,
    LATENCY_ARB_THRESHOLD_MS, LATENCY_ARB_CROSS_PCT,
    VOLATILITY_WINDOW, MIN_TICKS_FOR_VOL,
)

logger = logging.getLogger("pricing_engine")


# ─────────────────────────────────────────────────────────────────────
# SIGNAL TYPES
# ─────────────────────────────────────────────────────────────────────

class SignalType(Enum):
    """Types of trading signals the engine can generate."""
    NONE = "NONE"                  # No actionable signal
    MISPRICING_BUY = "MISPRICING"  # True prob significantly > PM price
    LATENCY_ARB = "LATENCY_ARB"   # Spot crossed strike, PM book is stale
    EXIT_MEAN_REVERT = "EXIT_MR"  # Mispricing gap has closed → exit
    EXIT_STOP_LOSS = "EXIT_SL"    # Position lost too much → exit
    EXIT_EXPIRY = "EXIT_EXPIRY"   # Contract about to expire → exit/settle


@dataclass
class TradingSignal:
    """A trading signal generated by the pricing engine."""
    signal_type: SignalType = SignalType.NONE
    asset_symbol: str = ""
    market_id: str = ""
    direction: str = ""           # "UP" or "DOWN"
    true_probability: float = 0.0
    pm_token_price: float = 0.0
    gap_pct: float = 0.0          # true_prob - pm_price
    spot_price: float = 0.0
    strike_price: float = 0.0
    volatility: float = 0.0       # Annualized σ
    time_to_expiry: float = 0.0   # Seconds until expiry
    pm_book_age_ms: float = 0.0   # How stale is the PM orderbook
    confidence: float = 0.0       # 0-1 confidence in the signal
    timestamp: float = field(default_factory=time.time)


# ─────────────────────────────────────────────────────────────────────
# VOLATILITY ESTIMATION
# ─────────────────────────────────────────────────────────────────────

def calculate_rolling_volatility(
    price_history: deque,
    window: int = VOLATILITY_WINDOW,
    min_ticks: int = MIN_TICKS_FOR_VOL
) -> Optional[float]:
    """
    Calculates the annualized volatility from tick-by-tick price data.
    
    Method:
    1. Take the last `window` price observations
    2. Compute log returns: r_i = ln(P_i / P_{i-1})
    3. Calculate standard deviation of log returns: σ_tick
    4. Annualize using observed tick frequency:
       σ_annual = σ_tick × √(ticks_per_year)
    
    Why log returns?
    - Log returns are additive across time periods
    - Normally distributed (approximately), which is a Black-Scholes assumption
    - Symmetric: a 10% gain and 10% loss have equal magnitude
    
    Args:
        price_history: deque of (timestamp, price) tuples
        window: number of recent ticks to use
        min_ticks: minimum observations required
    
    Returns:
        Annualized volatility as a decimal (e.g., 0.80 = 80% annual vol),
        or None if insufficient data.
    """
    if len(price_history) < min_ticks:
        return None

    # Extract the most recent `window` observations
    recent = list(price_history)[-window:]
    if len(recent) < min_ticks:
        return None

    timestamps = [t[0] for t in recent]
    prices = [t[1] for t in recent]

    # Compute log returns
    log_returns = []
    for i in range(1, len(prices)):
        if prices[i - 1] > 0 and prices[i] > 0:
            log_returns.append(math.log(prices[i] / prices[i - 1]))

    if len(log_returns) < 5:
        return None

    # Standard deviation of log returns (per-tick volatility)
    sigma_tick = float(np.std(log_returns, ddof=1))

    # Estimate tick frequency (ticks per second)
    total_time = timestamps[-1] - timestamps[0]
    if total_time <= 0:
        return None
    ticks_per_second = len(recent) / total_time

    # Annualize: σ_annual = σ_tick × √(ticks_per_year)
    # seconds_per_year = 365.25 * 24 * 3600 = 31,557,600
    seconds_per_year = 31_557_600
    ticks_per_year = ticks_per_second * seconds_per_year
    sigma_annual = sigma_tick * math.sqrt(ticks_per_year)

    # Sanity bounds: crypto vol typically 30%-200% annualized
    # But short-term can spike much higher; cap at 500%
    sigma_annual = max(0.01, min(sigma_annual, 5.0))

    return sigma_annual


# ─────────────────────────────────────────────────────────────────────
# TRUE PROBABILITY CALCULATION (Black-Scholes Binary)
# ─────────────────────────────────────────────────────────────────────

def calculate_true_probability(
    spot_price: float,
    strike_price: float,
    time_to_expiry_seconds: float,
    volatility: float,
    direction: str = "UP"
) -> float:
    """
    Calculates the risk-neutral probability that the asset will be
    above (UP) or below (DOWN) the strike price at contract expiry.
    
    Uses the Black-Scholes binary option / "cash-or-nothing" formula:
    
      d₂ = [ln(S/K) + (-½σ²)T] / (σ√T)
      
      P(S > K at expiry) = Φ(d₂)    for UP contracts
      P(S < K at expiry) = 1 - Φ(d₂) for DOWN contracts
    
    Where:
      S  = current spot price (from Binance/Coinbase average)
      K  = strike price (from Polymarket market metadata)
      T  = time to expiry in years (e.g., 5 min = 5/525600 years)
      σ  = annualized volatility (from rolling tick calculation)
      Φ  = standard normal cumulative distribution function
    
    Note: We omit the risk-free rate (r) since for sub-hour crypto
    contracts, the interest rate component is negligible (<0.00001%).
    
    Args:
        spot_price: Current spot price of the underlying
        strike_price: The target price level
        time_to_expiry_seconds: Seconds until contract expiration
        volatility: Annualized volatility (decimal)
        direction: "UP" (probability of finishing above) or "DOWN" (below)
    
    Returns:
        Probability as a decimal between 0.0 and 1.0
    """
    if spot_price <= 0 or strike_price <= 0:
        return 0.5  # Cannot calculate — return neutral

    if time_to_expiry_seconds <= 0:
        # Already expired — result is deterministic
        if direction == "UP":
            return 1.0 if spot_price > strike_price else 0.0
        else:
            return 1.0 if spot_price < strike_price else 0.0

    if volatility <= 0:
        return 0.5  # Cannot calculate without volatility

    # Convert time to years
    # 1 year = 365.25 days × 24 hours × 60 minutes = 525,960 minutes
    T = time_to_expiry_seconds / 31_557_600

    # Calculate d₂ (note: we use d₂ directly, not d₁)
    # d₂ = [ln(S/K) + (-0.5σ²)T] / (σ√T)
    #
    # The (-0.5σ²) term is the drift adjustment under risk-neutral pricing.
    # For short-term contracts, this term is tiny but we include it
    # for mathematical correctness.
    sqrt_T = math.sqrt(T)
    d2 = (math.log(spot_price / strike_price) + (-0.5 * volatility ** 2) * T) / (volatility * sqrt_T)

    # Φ(d₂) gives the probability the asset finishes above the strike
    prob_above = norm.cdf(d2)

    if direction == "UP":
        return float(prob_above)
    else:  # DOWN
        return float(1.0 - prob_above)


# ─────────────────────────────────────────────────────────────────────
# MISPRICING DETECTION
# ─────────────────────────────────────────────────────────────────────

def detect_mispricing(
    true_prob: float,
    pm_token_price: float,
    threshold: float = MISPRICING_THRESHOLD,
    exit_threshold: float = MISPRICING_EXIT_THRESHOLD,
    is_open_position: bool = False
) -> Tuple[SignalType, float]:
    """
    Detects mispricing between our calculated true probability
    and the Polymarket token price.
    
    Entry Logic:
    If true_prob - pm_price > threshold (default 8%), we have
    identified a significant edge. The market is underpricing the
    probability → BUY the token.
    
    Example:
      True Probability = 55% (our Black-Scholes calculation)
      PM Token Price   = 30¢ (market says 30% chance)
      Gap              = 25% → well above 8% threshold → BUY ✅
    
    Exit Logic:
    If the gap has narrowed to < exit_threshold (default 2%),
    the market has repriced and our edge is gone → EXIT.
    
    Args:
        true_prob: Our calculated probability (0-1)
        pm_token_price: Current Polymarket token price (0-1)
        threshold: Minimum gap to trigger entry
        exit_threshold: Maximum gap to trigger exit
        is_open_position: Whether we already hold this position
    
    Returns:
        Tuple of (SignalType, gap_percentage)
    """
    gap = true_prob - pm_token_price

    if not is_open_position:
        # Entry signal: gap must exceed threshold
        if gap > threshold:
            return SignalType.MISPRICING_BUY, gap
    else:
        # Exit signal: gap has closed below exit threshold
        if gap < exit_threshold:
            return SignalType.EXIT_MEAN_REVERT, gap

    return SignalType.NONE, gap


# ─────────────────────────────────────────────────────────────────────
# LATENCY ARBITRAGE DETECTION
# ─────────────────────────────────────────────────────────────────────

def detect_latency_arb(
    spot_price: float,
    strike_price: float,
    direction: str,
    pm_best_ask: float,
    pm_book_age_ms: float,
    threshold_ms: float = LATENCY_ARB_THRESHOLD_MS,
    cross_pct: float = LATENCY_ARB_CROSS_PCT
) -> Tuple[bool, float]:
    """
    Detects latency arbitrage opportunities.
    
    The Strategy (reverse-engineered from 0x8dxd / OHMO.AI):
    1. Spot price from Binance/Coinbase crosses the strike price
       in the favorable direction WITH momentum (not just touching)
    2. Polymarket's order book has NOT yet adjusted (book is stale)
    3. This creates a window where PM tokens are still cheap
       even though the probability of the event has jumped
    
    Why does this work?
    - Binance/Coinbase WebSocket data arrives in ~10-50ms
    - Polymarket CLOB updates may lag by 200-2000ms due to:
      • Polygon network latency
      • Human market makers being slower to react
      • PM's infrastructure processing pipeline
    - This creates a ~500ms+ window to exploit
    
    Momentum Confirmation (cross_pct):
    We require the spot price to cross the strike by at least 0.1%
    to filter out noise where the price just touches the strike and
    bounces back. This prevents false signals from high-frequency
    oscillations around the strike level.
    
    Args:
        spot_price: Current spot price from exchange feeds
        strike_price: Contract strike price
        direction: "UP" or "DOWN"
        pm_best_ask: Best ask price on Polymarket CLOB for YES token
        pm_book_age_ms: Age of the PM orderbook snapshot in milliseconds
        threshold_ms: Minimum book staleness to consider arb
        cross_pct: Minimum % the spot must cross strike by
    
    Returns:
        Tuple of (is_arb_opportunity, book_age_ms)
    """
    if strike_price <= 0:
        return False, 0.0

    # Step 1: Check if spot price has crossed the strike with momentum
    if direction == "UP":
        # For UP contracts, bullish if spot > strike
        cross_amount = (spot_price - strike_price) / strike_price
        favorable_cross = cross_amount > cross_pct
    else:
        # For DOWN contracts, bullish if spot < strike
        cross_amount = (strike_price - spot_price) / strike_price
        favorable_cross = cross_amount > cross_pct

    if not favorable_cross:
        return False, pm_book_age_ms

    # Step 2: Check if PM book is stale (hasn't reacted to the cross)
    book_is_stale = pm_book_age_ms > threshold_ms

    if not book_is_stale:
        return False, pm_book_age_ms

    # Step 3: Check if PM price is still low (hasn't adjusted)
    # If the cross is favorable and the PM YES token is still < 0.60,
    # there's likely an arb opportunity
    pm_not_adjusted = pm_best_ask < 0.60

    return (book_is_stale and pm_not_adjusted), pm_book_age_ms


# ─────────────────────────────────────────────────────────────────────
# MASTER SIGNAL EVALUATOR
# ─────────────────────────────────────────────────────────────────────

def evaluate_contract(
    spot_price: float,
    strike_price: float,
    direction: str,
    time_to_expiry_seconds: float,
    volatility: Optional[float],
    pm_best_ask: float,
    pm_midpoint: float,
    pm_book_age_ms: float,
    is_open_position: bool = False,
    asset_symbol: str = "",
    market_id: str = ""
) -> TradingSignal:
    """
    Master evaluator that runs all signal detection algorithms
    on a single contract and returns the highest-priority signal.
    
    Priority order:
    1. Latency Arb (fastest alpha, most time-sensitive)
    2. Mispricing (slower but more reliable)
    3. Exit signals (for open positions)
    
    Args:
        spot_price: Best spot price from exchanges
        strike_price: Contract's target price
        direction: "UP" or "DOWN"
        time_to_expiry_seconds: Seconds until expiry
        volatility: Annualized volatility (or None)
        pm_best_ask: Best ask on PM CLOB
        pm_midpoint: Midpoint price on PM CLOB
        pm_book_age_ms: Age of PM book update in ms
        is_open_position: Do we already hold this?
        asset_symbol: e.g., "BTC"
        market_id: Polymarket market ID
    
    Returns:
        TradingSignal with the recommended action
    """
    signal = TradingSignal(
        asset_symbol=asset_symbol,
        market_id=market_id,
        direction=direction,
        spot_price=spot_price,
        strike_price=strike_price,
        time_to_expiry=time_to_expiry_seconds,
        pm_token_price=pm_midpoint,
        pm_book_age_ms=pm_book_age_ms,
    )

    # ── Check if contract is about to expire (< 10 seconds left) ──
    if time_to_expiry_seconds < 10:
        signal.signal_type = SignalType.EXIT_EXPIRY
        signal.confidence = 1.0
        return signal

    # ── Use default volatility if we can't calculate it ──
    # 80% annual vol is a reasonable baseline for major cryptos
    vol = volatility if volatility else 0.80
    signal.volatility = vol

    # ── Calculate true probability ──
    true_prob = calculate_true_probability(
        spot_price, strike_price, time_to_expiry_seconds, vol, direction
    )
    signal.true_probability = true_prob

    # ── Strategy 1: Latency Arbitrage ──
    is_arb, book_age = detect_latency_arb(
        spot_price, strike_price, direction, pm_best_ask, pm_book_age_ms
    )
    if is_arb and not is_open_position:
        signal.signal_type = SignalType.LATENCY_ARB
        signal.gap_pct = true_prob - pm_midpoint
        # Confidence scales with book staleness and price cross magnitude
        stale_factor = min(pm_book_age_ms / 2000, 1.0)  # Max at 2s stale
        signal.confidence = min(0.95, 0.5 + stale_factor * 0.45)
        return signal

    # ── Strategy 2: Probability Mispricing ──
    mispricing_signal, gap = detect_mispricing(
        true_prob, pm_midpoint, is_open_position=is_open_position
    )
    signal.gap_pct = gap

    if mispricing_signal == SignalType.MISPRICING_BUY and not is_open_position:
        signal.signal_type = SignalType.MISPRICING_BUY
        # Confidence scales with gap size — bigger gap = more confident
        signal.confidence = min(0.90, 0.3 + (gap - MISPRICING_THRESHOLD) * 3)
        return signal

    if mispricing_signal == SignalType.EXIT_MEAN_REVERT and is_open_position:
        signal.signal_type = SignalType.EXIT_MEAN_REVERT
        signal.confidence = 0.85
        return signal

    signal.signal_type = SignalType.NONE
    return signal
